var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/publik/page.js")
R.c("server/chunks/ssr/_0wkd_69._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1t-buc0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yu2jwx._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rj-c_c._.js")
R.c("server/chunks/ssr/src_0oqwnwt._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_publik_page_actions_1-sft0g.js")
R.m(50432)
module.exports=R.m(50432).exports
