var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(portal)/kelola-periode/page.js")
R.c("server/chunks/ssr/_1kjini5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1t-buc0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yu2jwx._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rj-c_c._.js")
R.c("server/chunks/ssr/src_0oqwnwt._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/src_0qqti8h._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(portal)_kelola-periode_page_actions_05equ17.js")
R.m(87594)
module.exports=R.m(87594).exports
